version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bmstu_postgres
    environment:
      POSTGRES_USER: bmstu_user
      POSTGRES_PASSWORD: bmstu_password
      POSTGRES_DB: bmstu_lab_db
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bmstu_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: bmstu_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bmstu.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - bmstu_network

  minio:
    image: minio/minio:latest
    container_name: bmstu_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9090:9000"  
      - "9091:9001"  
    volumes:
      - minio_data:/data
    networks:
      - bmstu_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
  minio_data:

networks:
  bmstu_network:
    driver: bridge